메인 홈 포스트 리스트 구현 및 포스트 생성 기능 , 채널 생성 및 관리 기능 구현
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #13
Opened 2024-01-01 03:15 UTC by JuJangGwon

## 관련 이슈
- 이슈 링크: #4 , #12 

<br />

## 작업 내용

https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/assets/40955023/32eee3a5-1587-4d72-85e7-694c3ac08539

- [x] 채널 생성 - [특수빵, 조리빵, 식빵, 과자빵]
    * [전체보기/특수빵/과자빵/식빵/일반빵] 5개 채널을 추가했습니다.
- [x] 관리자 기능 - 관리자 채널 생성 함수 구현
    * 관리자 UI를 따로 구현 하지는 않았습니다. (채널 삭제는 API 문제로 구현이 불가능할거같습니다.)
- [x] 채널 선택 모달 구현
     * 드롭박스 형식으로 구현했습니다. 
- [x] 메인 홈 포스트 리스트 구현 
    * 포스트 아이템 로딩이 완료될 때 생성 트렌지션 효과를 구현했습니다. 
- [x] 포스트 생성 기능 구현
    * 기존 APi 필드에 포스트 body를 담을 부분이 없어서 title 필드에 {title : title, body :body} - json 타입으로 추가 했습니다.
- [x] 메인 홈 하단 메뉴바 구현
    * 4번 째, 포스트 생성만 연결되었고, 누를 시 포스트 생성 페이지로 이동 

<br />

## 특이 사항
- 이번 PR은 실수로 기능 단위, 이슈 단위로 끊지 못했습니다 (ㅎㅎ..) 다음부턴 세부적으로 나눠서 올리겠습니다. 
- token은 임시 super계정 로그인 기능을 구현하여 받은 토큰을 사용하고 있습니다. 
- 포스트 업로드 페이지에서 내용 작성 placeholder는 추후 위지윅 편집기 라이브러리 도입 예정으로 디자인 하지 않았습니다. 
 
<br />

## 리뷰 요구사항 
- 아직 컨벤션이 익숙하지 않아 컨벤션이 적용되지 않은 곳들이 있습니다. 혹여나 발견된다면 알려주세요 
- 추상화, 불 필요한 로직 및 코드, 개선 사항이 보인다면 메세지 남겨주세요.

2024-01-02 03:47 UTC, lja0395 commented on src/apis/postApis.ts
> +      {headers: {'Authorization': `bearer ${token}`,'Content-Type': 'multipart/form-data'}})
P5 : deletePost 코드와 통일성을 줄 수 있을 거 같습니다!
```
.post(CREATE_POST_PATH, formData,{
    headers: {'Authorization': `bearer ${token}`,'Content-Type': 'multipart/form-data'}
})

2024-01-02 03:58 UTC, Yoonkyoungme reviewed
**P4**
전체적으로 들여쓰기가 잘못 되어 있거나, className, onClick 등에서 코드 형식이 일관되지 않습니다😭
```jsx
<p className ="text-[0.625rem] mt-6 mb-1 text-[#959595]">어떤 종류의 빵인가요?* 1개 선택</p>
<div className ='flex gap-2'>

onClick ={()=>setSelectedBread(item as BreadType)}>
```

VSCode에서 lint와 Prettier의 `"editor.formatOnSave": true` 옵션 설정이 안 되어 있는 것 같아요! 확인해 보셔요~

2024-01-02 03:58 UTC, Yoonkyoungme commented on src/apis/channelApis.ts
**P2**
전체적으로 마지막 라인에 개행이 안 되어 있어 ⛔️ 이 표시가 남아 있네요.
큰 문제는 발생하지 않지만, merge 시 코드가 충돌할 가능성이 있습니다.
[VSCode에서 EOL 설정](https://2mukee.tistory.com/m/818)하는 거 추천드려요
https://bellasimi.github.io/error/Error-파일-끝에서-줄바꿈하는-이유/

2024-01-02 11:58 UTC, lunarmoon7 requested changes

2024-01-02 12:03 UTC, lunarmoon7 commented on src/pages/Home/components/feed/PostItem.tsx
> +                    </div>
p1:
같은 구조의 코드가 반복되는 것 같아요. 스타일은 동일한데, 사용되는 아이템(데이터)이 다르네요.
이 부분은 공통 컴포넌트로 추상화를 진행하면 좋을 것 같아요.

2024-01-02 12:05 UTC, lunarmoon7 requested changes
기능 구현하시느라 고생 많으셨습니다.

코드 리뷰를 하면서, 전체적으로 코드의 통일성이 갖춰지지 않은 느낌입니다.(띄어쓰기, 들여쓰기 등..)

코드의 가독성 측면에서는, tailwindcss의 단점을 보완하고자 도입한 tw-macro가 적용되어 있지 않아서 '어떤 구조를 담당하는 컴포넌트인지' 알기가 어려웠습니다.

또한, 추상화를 할 수 있는 코드는 추상화를 적극적으로 고려해보시면 좋을 것 같습니다.

개인 프로젝트라면 상관이 없으나, 팀 프로젝트이기에 과제 리뷰와 다르게 말씀드린 점 양해 부탁드립니다 ㅎㅎ;

2024-01-03 00:30 UTC, Yoonkyoungme requested changes

2024-01-03 00:30 UTC, Yoonkyoungme commented on src/pages/Home/components/feed/PostItem.tsx
> +    }
**P3**
해당 로직은 지난 번 스크럼 때 말씀해 주신 것처럼  utils에 정의하면 좋을 것 같아요!

**P5**
getPostLiveTime 함수에서 현재 시간과 게시글 작성 시간을 비교하는 로직이 조금 복잡해 보입니다.
Date 객체 간의 차이를 직접 계산하는 대신 getTime 메소드를 사용하여 두 시간의 차이를 밀리초 단위로 계산하는건 어떤가요? 또한, 각 시간 단위를 상수로 선언하여 가독성을 높일 수 있을 것 같아요. 

```suggestion
function getPostLiveTime(createdAt: string) {
    const MINUTE = 60;
    const HOUR = MINUTE * 60;
    const DAY = HOUR * 24;
    
    const compareTime = Math.floor((nowTime.getTime() - createdTime.getTime()) / 1000);

    if (compareTime < MINUTE) {
        return compareTime === 0 ? '방금 전' : `${compareTime}분 전`;
    } else if (compareTime < HOUR) {
        return `${Math.floor(compareTime / MINUTE)}시간 전`;
    } else if (compareTime < DAY) {
        return `${Math.floor(compareTime / HOUR)}일 전`;
    } else {
        return `${createdTime.getFullYear().toString().slice(2,4)}.${createdTime.getMonth()+1}.${createdTime.getDate()}`;
    }
}

```

https://carrotweb.tistory.com/163

2024-01-03 00:30 UTC, Yoonkyoungme commented on src/pages/Home/index.tsx
> +    },[nowChannel]);
**P3**
useEffect를 사용하셨는데, 해당 부분에 아무 동작도 정의되지 않았습니다. 이 부분이 필요 없다면 제거하거나, 필요한 동작이 있다면 정의가 필요할 것 같습니다.

2024-01-03 00:30 UTC, Yoonkyoungme commented on src/pages/Home/index.tsx
> +    const [nowCreate,setNowCreate] = useState<boolean>(false);
**P5**
nowCreate라는 상태의 이름이 조금 더 직관으로 바꾸면 어떨까요? (ex: `isCreatingPost`)

2024-01-03 01:14 UTC, lunarmoon7 commented on src/pages/Home/components/bottom-navbar/index.tsx
> +            <img className = "w-6 h-7 my-auto" src={ScrollTopIcon}/>
```
<NavButton width={} height={} imgSrc={} />

// NavButton
<button>
  <img src={imgSrc} {width랑 height 적용하기} />
</button>
```

약간 이런 식으로 저는 생각을 해보았습니다.

2024-01-03 11:03 UTC, lja0395 approved these changes

2024-01-03 13:15 UTC, JuJangGwon commented on src/pages/Home/components/feed/PostItem.tsx
> +    }
이 부분은 다음 pr에 반영될거같습니다.

2024-01-03 14:51 UTC, JuJangGwon commented on src/pages/Home/index.tsx
> +            }
ReactRouter 도입으로 해당 코드는 제외하는 방향으로 수정했습니다!

2024-01-03 17:12 UTC, JuJangGwon commented on src/pages/Home/components/createPost/index.tsx
> +import { AdminLogin } from '@/apis/mockingApis';
merge 할 떄 로그인 코드와 병합하면서 해결하겠습니다

2024-01-04 00:53 UTC, lunarmoon7 approved these changes

2024-01-04 00:54 UTC, Yoonkyoungme approved these changes

2024-01-04 01:00 UTC, merged