로그인 기능 구현
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #18
Opened 2024-01-01 15:07 UTC by lja0395

## 관련 이슈
- #5 

<br />

## 작업 내용

https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/assets/99376069/bafb53e6-206b-4dbf-a7fd-f80c6bf322e8

- 회원가입 된 이메일과 비밀번호로 로그인을 하면 token값이 출력되고 localStorage에 저장됩니다.

<br />

## 특이 사항
- cookie를 사용해서 token을 저장하는 방법도 추후에 고민
- 로그인 화면에서 '계정이 없으신가요?' 버튼을 누르면 회원가입 페이지로 이동할 수 있도록 구현할 것

<br />

## 리뷰 요구사항 (선택)
- 리뷰 중점 사항: 리뷰어가 특히 집중해서 봐야 할 부분이 있나요?
- 추가 검토 사항: 코드, 디자인, 구현 방식 등에 대한 추가적인 검토가 필요한 사항이 있나요?
- 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?

2024-01-02 02:25 UTC, lunarmoon7 commented on src/pages/login/LoginForm.tsx
> +      console.log('response:', response);
p1:
콘솔 함수는 삭제 부탁드립니다!

2024-01-02 02:25 UTC, lunarmoon7 commented on src/pages/login/LoginStyles.ts
> +export const button = tw.button`w-full py-2 bg-white border border-gray-300 text-black rounded-full mt-4 hover:bg-brand-primary hover:text-white hover:border-brand-primary transition duration-300 eas
p3:
리액트에서 컴포넌트는 보통 파스칼케이스로 작성하는 것으로 알고 있어요!
그래서 해당 코드도 컴포넌트의 역할을 수행하는 것으로 보여서, 파스칼 케이스로 통일하면 어떨까요?

2024-01-02 02:25 UTC, lunarmoon7 commented on src/pages/login/LoginForm.tsx
> +import * as styles from '@/pages/login/LoginStyles';
p5:
사소한 의견이지만, styles도 Styles와 같이 파스칼 케이스로 표현하면 컴포넌트에 좀 더 통일성을 부여할 수 있지 않을까? 하는 생각이 드네요!

e.g. <Styles.Container>, <Styles.Form>, <Styles.Input>, ...

2024-01-02 02:29 UTC, Yoonkyoungme commented on src/pages/login/LoginForm.tsx
> +      console.log('response:', response);
**P3**
console.log를 지워서 pr 올리는 것이 좋을 것 같습니다! (token 값이 console에서 보이네요😭)

2024-01-02 02:29 UTC, Yoonkyoungme commented on src/pages/login/LoginForm.tsx
> +export default LoginForm;
**P2**
전체적으로 마지막 라인에 개행이 안 되어 있네요.
큰 문제는 발생하지 않지만, merge 시 코드 충돌할 가능성이 있습니다.
[VSCode에서 EOL 설정](https://2mukee.tistory.com/m/818)하는 거 추천드려요
https://bellasimi.github.io/error/Error-파일-끝에서-줄바꿈하는-이유/

2024-01-02 02:29 UTC, Yoonkyoungme commented on src/pages/login/LoginStyles.ts
**P5, ASK**
twin.macro를 사용해 주셨군요! 스타일 관련 파일을 따로 빼서 사용하신 이유가 있을까요?
저는 공통으로 사용되는 것만 따로 styles 디렉터리에 정의하여 사용하는 편입니다!
https://fe-developers.kakaoent.com/2022/221013-tailwind-and-design-system/

2024-01-02 02:31 UTC, JuJangGwon requested changes

2024-01-02 02:31 UTC, JuJangGwon commented on src/pages/login/LoginForm.tsx
> +import React, { useState } from 'react';
P1 : React 라이브러리는 현재 코드에서 사용하지 않고 있으니 지우셔도 될 거 같습니다.

2024-01-02 02:31 UTC, JuJangGwon commented on src/pages/login/LoginForm.tsx
> +function LoginForm({}: Props) {
P1 : 현재 Props 역시 ? 현재 컴포넌트에서 사용하지 않고 있어서 지우셔도 될 거 같습니다.

2024-01-02 04:09 UTC, lunarmoon7 requested changes
변경 요청

2024-01-02 11:51 UTC, Yoonkyoungme requested changes

2024-01-02 11:51 UTC, Yoonkyoungme commented on src/apis/login.ts
> +  }
**P2**

전체적으로 마지막 라인에 개행이 안 되어 있네요.
큰 문제는 발생하지 않지만, merge 시 코드가 충돌할 가능성이 있습니다.
[VSCode에서 EOL 설정](https://2mukee.tistory.com/m/818)하는 거 추천드려요
https://bellasimi.github.io/error/Error-파일-끝에서-줄바꿈하는-이유/

2024-01-02 15:37 UTC, Yoonkyoungme approved these changes

2024-01-03 00:33 UTC, JuJangGwon approved these changes

2024-01-03 01:44 UTC, lunarmoon7 approved these changes
승인

2024-01-03 01:45 UTC, JuJangGwon approved these changes

2024-01-03 01:45 UTC, Yoonkyoungme approved these changes

2024-01-03 01:47 UTC, merged