Feature/search
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #21
Opened 2024-01-04 01:48 UTC by lunarmoon7

## 관련 이슈
- 이슈 링크: https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/issues/19#issue-2061855150

<br />

## 작업 내용

https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/assets/101445377/3d0e2370-9fbe-42db-a782-af1f723c0288

- 검색을 할 수 있습니다.
- 사용자 또는 전체(사용자 & 포스트) 필터를 통해 검색할 수 있습니다.
- 검색 결과가 없을 경우, 특정 문구가 보여집니다.
- 전체 검색 시, 사용자는 가로 슬라이드 형식으로 보여집니다.
- 사용자 검색 시, 사용자는 세로 형식으로 보여집니다.

<br />

## 특이 사항
- router 처리는 진행하지 않았습니다.
  - e.g. 포스트 클릭, 사용자 클릭
 
<br />

## 리뷰 요구사항 (선택)
- 리뷰 중점 사항: 예외처리가 되지 않은 부분이 있을까요? 컨벤션이 적절하게 지켜졌나요?
- 추가 검토 사항: 코드, 디자인, 구현 방식 등에 대한 추가적인 검토가 필요한 사항이 있나요?
- 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?

2024-01-04 12:44 UTC, JuJangGwon requested changes

2024-01-04 12:44 UTC, JuJangGwon commented on src/pages/search/components/FilteredList.tsx
> +          />
P5 : 저는 객체 분해할당 했을 때 2개 이상 나눠진다면 분해할당을 많이 활용하는 편인데, 이러면 조금 더 간결해지는거 같은 느낌이 들더라구요. 이거는 스타일차이이니 적용안하셔도 될 거 같습니다. 
```suggestion
  users?.map(({image,fullName,email) => (
          <FilteredUser
            image={image}
            fullName={fullName}
            email={email}
          />

2024-01-04 12:44 UTC, JuJangGwon commented on src/pages/search/index.tsx
> +    isLoading,
P3 : IsLoading 변수가 사용이 되지 않고 있는거 같습니다.

2024-01-05 00:51 UTC, lunarmoon7 commented on src/pages/search/components/FilteredList.tsx
> +          />
👍

2024-01-05 00:52 UTC, lunarmoon7 commented on src/pages/search/index.tsx
> +    isLoading,
이 부분은 추후에 API 요청에 딜레이가 생길 시, Spinner 형태로 애니메이션을 보여줄 수 있을 것 같아 삭제하지 않았습니다 ㅎㅎ

2024-01-05 01:06 UTC, JuJangGwon approved these changes

2024-01-05 01:07 UTC, merged

2024-01-05 01:08 UTC, lja0395 approved these changes

2024-01-05 01:10 UTC, Yoonkyoungme requested changes

2024-01-05 01:10 UTC, Yoonkyoungme commented on src/pages/search/components/FilteredList.tsx
> +                ))}
**P3**
users?.map 및 posts?.map에서 컴포넌트에 고유한 key 값을 제공하면 좋을 것 같아요!