팔로우, 팔로우 취소 기능 구현
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #31
Opened 2024-01-08 02:43 UTC by lunarmoon7

## 관련 이슈
- 이슈 링크: https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/issues/30

<br />

## 작업 내용
- 팔로우, 팔로우 취소 기능을 구현했습니다.
  - 팔로우 버튼을 눌러서 동작을 수행할 수 있습니다.

<br />

## 특이 사항
- 팔로우 요청 또는 취소 시, 낙관적 업데이트는 적용하지 않았습니다.
  - 추후 react-query를 사용하게 된다면, 그때 적용해도 될 것 같아 보류했습니다. 이에 대해서 **많은 의견 부탁드립니다!**

<br />

## 리뷰 요구사항 (선택)
- 리뷰 중점 사항: 코드 컨벤션에 어긋나는 부분이 있나요?
- 추가 검토 사항: 코드, 디자인, 구현 방식 등에 대한 추가적인 검토가 필요한 사항이 있나요?
- 논의가 필요한 부분
  - **팔로잉, 팔로워를 눌렀을 때 사용자 목록이 나타나는 디자인을 추가하는 건 어떨까요?**
  - API 요청 시 **토큰을 사용하는 함수**가 꽤 있는 것 같습니다. 이를 **하나의 상수로 불러와서 사용**하는 건 어떨까요? 너무 과할까요? 
![스크린샷 2024-01-08 11 42 27](https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/assets/101445377/54c19871-e3bf-47c6-9d61-964665b4c4b4)

2024-01-09 01:31 UTC, Yoonkyoungme approved these changes
> 팔로잉, 팔로워를 눌렀을 때 사용자 목록이 나타나는 디자인을 추가하는 건 어떨까요?

좋은 아이디어네요!!

> API 요청 시 토큰을 사용하는 함수가 꽤 있는 것 같습니다. 이를 하나의 상수로 불러와서 사용하는 건 어떨까요? 너무 과할까요?

저도 휘식님 의견처럼 토큰을 사용하는 로직을 분리해서 사용하는 것에 동의합니다!
api.ts 파일에 토큰이 필요한 API 요청들을 위한 인스턴스와 토큰이 필요하지 않은 API 요청들을 위한 인스턴스로 나누어 생성하고, axios interceptors를 이용해서 헤더에 토큰을 설정하는 방법도 있을 것 같습니다😊 https://growing-jiwoo.tistory.com/85
```typescript
import axios from 'axios'

// 토큰이 필요한 요청을 위한 인스턴스
const axiosInstanceWithToken = axios.create({
  baseURL: `${import.meta.env.VITE_BASE_URL}:${import.meta.env.VITE_APP_PORT}`,
  timeout: 5000,
  headers: { 'Content-Type': 'application/json' }
})

axiosInstanceWithToken.interceptors.request.use(config => {
  const token = localStorage.getItem('token')
  const parsedToken = JSON.parse(token as string)
  config.headers['Authorization'] = `Bearer ${parsedToken}`
  return config
}, error => {
  return Promise.reject(error)
})

// 토큰이 필요하지 않은 요청을 위한 인스턴스
const axiosInstance = axios.create({
  baseURL: `${import.meta.env.VITE_BASE_URL}:${import.meta.env.VITE_APP_PORT}`,
  timeout: 5000,
  headers: { 'Content-Type': 'application/json' }
})

export { axiosInstanceWithToken, axiosInstance }

```

이 부분은 현재 구현하고 있는 기능들 merge 하고, 전체적인 리팩터링 할 때 시도해 보면 좋을 것 같아요!

2024-01-09 01:31 UTC, Yoonkyoungme commented on src/pages/Profile/components/profile-edit-drawer/ProfileNameForm.tsx
>      }
**P5**
에러 메시지를 별도의 상수로 관리 하는건 어떤가요? (지금 코드도 좋습니다! P5 정도의 가벼운 의견입니다😊)
```suggestion
const ERRORS = {
  EMPTY_FULLNAME: '실명을 입력해주세요.',
  LONG_FULLNAME: '실명은 6자 이내로 입력해주세요.',
  EMPTY_USERNAME: '사용자 명을 입력해주세요.',
  LONG_USERNAME: '사용자 명은 8자 이내로 입력해주세요.',
}

validate: (values) => {
  const errors = {} as Record<string, string>

  if (values.fullName.length === 0) {
    errors.fullName = ERRORS.EMPTY_FULLNAME
  } else if (values.fullName.length > 6) {
    errors.fullName = ERRORS.LONG_FULLNAME
  }

  .....
  return errors
}
```

2024-01-09 01:47 UTC, Yoonkyoungme requested changes

2024-01-09 01:47 UTC, Yoonkyoungme commented on src/pages/profile/index.tsx
> +import { useParams } from 'react-router-dom'
**P3**
컨벤션처럼 useParms를 import하는 부분을 상단에 위치시키면 좋을 것 같아요!

2024-01-09 03:16 UTC, JuJangGwon approved these changes

2024-01-09 03:30 UTC, JuJangGwon commented
> 팔로잉, 팔로워를 눌렀을 때 사용자 목록이 나타나는 디자인을 추가하는 건 어떨까요?
좋습니다! 인스타/페이스북 등을 참고하면 좋을 듯 합니다.
> API 요청 시 토큰을 사용하는 함수가 꽤 있는 것 같습니다. 이를 하나의 상수로 불러와서 사용하는 건 어떨까요? 너무 과할까요?
윤경님이 얘기해주신 axios interceptor를 활용하면 좋을거 같네요

2024-01-09 04:55 UTC, lja0395 approved these changes

2024-01-09 05:17 UTC, lunarmoon7 commented on src/pages/Profile/components/profile-edit-drawer/ProfileNameForm.tsx
>      }
좋습니다! 에러 메시지가 많아서, 따로 관리하면 코드가 깔끔해지고 의미도 명확해질 것 같네요!

2024-01-10 00:18 UTC, Yoonkyoungme approved these changes

2024-01-10 02:28 UTC, merged