알림 기능 구현
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #32
Opened 2024-01-08 05:07 UTC by Yoonkyoungme

## 관련 이슈
- 이슈 링크: #9

<br />

## 작업 내용

https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/assets/100656920/12eedd03-60ce-433d-8827-5dc340b4af51

- 알림 기능 구현
- 댓글 추가 시 알림 생성

<br />

## 특이 사항
- 프로젝트 실행에 영향을 미치는 중요한 변경사항이나 주의사항 등을 기술해 주세요. (작성중)
 
<br />

## 리뷰 요구사항 (선택)
- 리뷰 중점 사항: 리뷰어가 특히 집중해서 봐야 할 부분이 있나요?
- 추가 검토 사항: 코드, 디자인, 구현 방식 등에 대한 추가적인 검토가 필요한 사항이 있나요?
- 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?

2024-01-09 01:02 UTC, lunarmoon7 requested changes

2024-01-09 01:02 UTC, lunarmoon7 commented on src/components/notifications/NotificationModal.tsx
> +  }, [isOpen, onClose])
p5:
사용자 목록을 보여주는 곳에서도 모달을 사용할 것 같아요. 
그래서 리팩토링할 때, 모달을 열고 닫는 이 로직을 커스텀 훅으로 만드는 것은 어떨까? 혼자 생각을 해봤습니다 ㅎㅎ

2024-01-09 01:34 UTC, Yoonkyoungme commented on src/components/notifications/NotificationItem.tsx
> +      <div className="mr-4 w-12 h-12 rounded-full overflow-hidden">
좋습니다 ~~~!

2024-01-09 01:36 UTC, Yoonkyoungme commented on src/components/notifications/NotificationModal.tsx
> +  }, [isOpen, onClose])
오호! 의견 감사합니다! 커스텀 훅으로 만들어 보겠습니다.

2024-01-09 03:24 UTC, JuJangGwon approved these changes

2024-01-09 04:54 UTC, lja0395 approved these changes

2024-01-09 05:25 UTC, lunarmoon7 approved these changes

2024-01-10 01:18 UTC, lunarmoon7 approved these changes

2024-01-10 01:19 UTC, merged