포스트 수정 페이지에 이미지 변경, 채널변경 기능 추가
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #33
Opened 2024-01-08 16:09 UTC by JuJangGwon

## 관련 이슈
- 이슈 링크: #28

<br />

## 작업 내용

<img width="296" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/assets/40955023/b9c004f2-b48e-48f4-a84f-cff3f512757e">

<br />

- [x] 포스트 수정페이지에서 타이틀 이미지 추가 및 변경 기능 추가
- [x] 채널 변경 버튼 추가 

<br />

## 특이 사항
- 포스트 상세보기 & 포스트 리스트 중 카드에 있는 글 내용이 이상하게 뜨는 것은 #29과 병합하면 해결 되는 문제여서 따로 수정하지는 않았습니다. 
 
<br />

2024-01-09 01:10 UTC, lunarmoon7 requested changes

2024-01-09 01:10 UTC, lunarmoon7 commented on src/pages/PostEdit/index.tsx
> +      console.log(details)
p1:
주석과 콘솔함수는 지워주세요!

2024-01-09 01:10 UTC, lunarmoon7 commented on src/pages/PostEdit/index.tsx
> +              : '빵 이미지를 첨부 해주세요.'}
p5:
image가 있다면, image 내부에 name(image.name)이 없을 수도 있나요?
이 부분에 대해서 제가 정확히 몰라서, 로직을 왜 1-depth 더 가져 가셨는지 궁금합니다.

2024-01-09 01:27 UTC, JuJangGwon commented on src/pages/PostEdit/index.tsx
> +              : '빵 이미지를 첨부 해주세요.'}
input에는 이미지가 없는 경우, 서버로부터 이미지(initialData)를 받아온 경우,  사용자가 파일입력 이벤트를 통해 이미지를 입력한 경우  3가지 가 있습니다. 여기서  파일 입력 이벤트로 넣은 파일은 파일 이름이 제공되지만,  서버에 올라간 이미지는 파일이름을 제공하지 않아서, 서버로부터 받은 이미지는 '등록된 이미지가 있습니다' 문구가 나오게 따로 예외처리했습니다.

2024-01-09 03:57 UTC, JuJangGwon commented on src/pages/PostEdit/index.tsx
> +      console.log(details)
휘식님 과거의 코드를 리뷰 하신거 같습니다. 해당 주석과 콘솔함수는 
[b246b](https://github.com/prgrms-fe-devcourse/FEDC5_Bakers101_changyu/pull/33/commits/b246b606b5320b1b0963d955839bded9904d0148) 커밋때 수정됐었습니다.

2024-01-10 01:08 UTC, lja0395 approved these changes

2024-01-10 01:14 UTC, Yoonkyoungme approved these changes

2024-01-10 01:19 UTC, lunarmoon7 approved these changes

2024-01-10 01:26 UTC, merged