로그인 & 회원가입 이동안내 모달 구현 및 연결
prgrms-fe-devcourse/FEDC5_Bakers101_changyu pull request #49
Opened 2024-01-11 00:33 UTC by JuJangGwon

## 관련 이슈
- 이슈 링크: #34

<br />

## 기능 요약
- 로그인, 회원가입 이동 안내 모달 구현

<br />

## 상세 작업 내용
- [x] 로그인, 회원가입 이동 안내 모달 구현
- [x] 로그인 및 회원가입 라우팅 기능 구현 

<br />

## 리뷰 요구사항 (선택)
- 리뷰 중점 사항: 리뷰어가 특히 집중해서 봐야 할 부분이 있나요?
- 추가 검토 사항: 코드, 디자인, 구현 방식 등에 대한 추가적인 검토가 필요한 사항이 있나요?
- 논의가 필요한 부분: 코드 리뷰 중 논의가 필요해 보이는 부분은 무엇인가요?

2024-01-11 04:43 UTC, Yoonkyoungme commented on src/components/to-auth-route-modal/index.tsx
> +        <Link className="px-4 py-1 rounded-md text-white bg-[#9F8170]" to ='/login' onClick={closeModal}>
**P4**

버튼 스타일 속성이 중복되어 사용되는데, 이 부분을 별도로 빼서 재사용 하면 좋을 것 같습니다!

2024-01-11 04:45 UTC, Yoonkyoungme commented on src/components/to-auth-route-modal/index.tsx
> +      <p className='text-center text-lg font-semibold'> 아직 Bakers101 회원이 아니신가요?</p>
**P4**

웹 접근성을 높이기 위해 p 태그를 h2 태그로 변경하는 것도 추천드립니다!

2024-01-11 04:51 UTC, lunarmoon7 requested changes

2024-01-11 04:51 UTC, lunarmoon7 commented on src/pages/login/LoginForm.tsx
> +      setLogin()
p1: 
setLogin을 사용자 인증 API 요청으로 처리하는 것으로 수정하면 될 것 같네유

2024-01-11 04:51 UTC, lunarmoon7 commented on src/pages/home/components/header/index.tsx
> +  const {isLogin, openModal} = useAuthModalStore()
p5:
openModal과 toggleModal이 같은 역할을 수행하는 건가요??

2024-01-11 04:58 UTC, lunarmoon7 commented
> 지금로그인, 회원가입 이동 안내 모달의 폴더명을 to-auth-route-modal 라고 만들어봤는데.. 혹시 적절할까요?

저는 윤경님이 말씀해주신 이름도 좋고, auth-check-modal도 좋을 것 같습니다!

2024-01-12 00:59 UTC, lja0395 approved these changes

2024-01-12 00:59 UTC, lja0395 commented on src/pages/login/LoginForm.tsx
> +  const {setLogin} = useAuthModalStore()
P5
`{ setLogin }` 으로 고치면 좋을 거 같습니다!

2024-01-12 03:24 UTC, lunarmoon7 approved these changes

2024-01-12 03:24 UTC, Yoonkyoungme approved these changes

2024-01-12 03:24 UTC, merged